import NavBar from "./NavBar";
import Head from "next/head";
import Footer from "./Footer";
const Layout = ({ active, textColor, children }) => {
  const links=[
    {
      link: "#About",
      title: "About",
    },
    {
      link: "#Work",
      title: "Work"
    },
    {
      link: "#Contact",
      title: "Contact",
    },
  ];
  return (
    <>
      <Head>
        <title>William Suarez &apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar 
        extended
        color={process.env.primaryColor}
        active={active}
        logo="WS"
        links={links}
        textColor= {textColor}
       
      />
      {children}
      <Footer 
        links={links}
        title="William Suarez"
        color={process.env.primaryColor}
        sectionsTitle="thanks for your visit!"
        copyRightText="© 2022 william Suarez"
        icons={[
          {
            link : 'https://es.stackoverflow.com/users/185054/william-suarez',
            iconSrc : '/img/stack-overflow.svg',
          },
          {
            link : 'https://www.linkedin.com/in/williamsuarezdev/',
            iconSrc : '/img/linkedin.svg',
          },
          {
            link : 'https://github.com/willisq',
            iconSrc : '/img/github.svg',
          }
        ]}
      />
    </>
  );
}

export default Layout;
